[package]
name = "telluris-surface"
version = "0.1.0"
authors = ["Sébastien Guimmara <sguimmara@pobox.com>"]
edition = "2018"

[dependencies]
telluris-core = { path= "../telluris_core" }
log = "0.4.6"