[package]
name = "telluris-types"
version = "0.1.0"
authors = ["sguimmara"]
edition = "2018"

[dependencies]
num = "0.2.0"
nalgebra-glm = "0.3.0"

[dev-dependencies]
rand = "0.6.5"
quickcheck = "0.8"
quickcheck_macros = "0.8"